services:
  laravel-backend-fcm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PUBLIC_PORT}:8080"
    env_file: .env
    environment:
      - DB_DATABASE=/var/www/html/storage/sqlite/database.sqlite
    volumes:
      - ./storage/sqlite:/var/www/html/storage/sqlite
      - ./hapy-vernetzt-app-firebase-adminsdk.json:/var/www/html/hapy-vernetzt-app-firebase-adminsdk.json
