services:
  laravel-backend-fcm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PUBLIC_PORT}:8080"
    env_file: .env
    environment:
      - AUTORUN_ENABLED=true
      - PHP_OPCACHE_ENABLE=1
      - DB_DATABASE=/var/www/html/storage/sqlite/database.sqlite
    volumes:
      - sqlite_data:/var/www/html/storage/sqlite
      - ./firebase-admin-sdk.json:/var/www/html/firebase-admin-sdk.json

volumes:
  sqlite_data:
