services:
  laravel-backend-fcm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PUBLIC_PORT}:8080"
    env_file: .env
    volumes:
      - /database/database.sqlite:/database/database.sqlite
      - /hapy-vernetzt-app-firebase-adminsdk.json:/hapy-vernetzt-app-firebase-adminsdk.json